name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            checkTarget: true
          - os: ubuntu-latest
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}, os: ${{ matrix.os }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Build handling-errors
        run: dotnet build
        working-directory: exercises/handling-errors/solution/Worker

      - name: Check format handling-errors
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes
        working-directory: exercises/handling-errors/solution/Worker

      - name: Build non-retryable-err-types
        run: dotnet build
        working-directory: exercises/non-retryable-err-types/solution/Worker

      - name: Check format non-retryable-err-types
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes
        working-directory: exercises/non-retryable-err-types/solution/Worker

      - name: Build rollback-with-saga
        run: dotnet build
        working-directory: exercises/rollback-with-saga/solution/Worker

      - name: Check format rollback-with-saga
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes
        working-directory: exercises/rollback-with-saga/solution/Worker